"""Turns a finished study into a written report and a figure.

The report is the actual deliverable of an autoresearch system. A leaderboard
says what won; a report says what was learned, what was ruled out, and how much
to trust the number -- which is what a human needs in order to act on it.

Three rules this writer follows, all of them about not overclaiming:

* The selected model's validation score and its held-out score are always shown
  together. One without the other invites reading selection noise as skill.
* Rejected and inconclusive experiments get their own sections. A loop that
  reports only its winners is a loop you cannot audit.
* The selection gap is stated in plain words, including when it is unflattering.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # no display in a headless run
import matplotlib.pyplot as plt  # noqa: E402

from .loop import StudyReport  # noqa: E402

# Colour-blind-safe, readable in both light and dark contexts.
INK = "#1f2933"
MUTED = "#8a94a6"
ACCEPT = "#2d7d5a"
REJECT = "#c2543d"
INCONCLUSIVE = "#c99a2e"
INCUMBENT = "#2b6cb0"


def write_report(report: StudyReport, out_dir: Path | None = None) -> Path:
    out_dir = Path(out_dir or report.config.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{report.config.name}-report.md"
    path.write_text(render_markdown(report), encoding="utf-8")
    return path


def render_markdown(report: StudyReport) -> str:
    ledger = report.ledger
    lines: list[str] = []
    add = lines.append

    add(f"# Autoresearch report — {report.config.name}")
    add("")
    add(f"*Generated by the `mlresearch` harness plugin. "
        f"{len(ledger.entries)} experiments in {report.elapsed:.1f}s.*")
    add("")

    # ------------------------------------------------------------- headline
    add("## Result")
    add("")
    if report.incumbent is None:
        add("No experiment was accepted. Every proposal either failed or could not be "
            "distinguished from the baseline.")
        add("")
    else:
        incumbent = report.incumbent
        add(f"**Selected pipeline:** `{incumbent.experiment.label}`")
        add("")
        add(f"- Validation (repeated stratified CV): "
            f"**{incumbent.result.val_mean:.4f}** ± {incumbent.result.val_std:.4f} "
            f"over {len(incumbent.result.fold_scores)} folds")
        if report.holdout_score is not None:
            add(f"- Held-out test set (scored once, after selection): "
                f"**{report.holdout_score:.4f}**")
            gap = report.selection_gap
            add(f"- Selection gap (validation − held-out): **{gap:+.4f}**")
        add(f"- Promoted through {len(ledger.accepted())} accepted experiment(s)")
        add("")
        add("Full specification:")
        add("")
        add("```json")
        import json
        add(json.dumps(incumbent.experiment.spec, indent=2, default=str))
        add("```")
        add("")

    # ------------------------------------------- the selection-rule finding
    if report.selection_gap is not None and report.greedy_gap is not None:
        add("## Did the statistical gate earn its cost?")
        add("")
        add("Two selection rules, scored on the same held-out set:")
        add("")
        add("| Rule | Chose | Validation | Held-out | Gap |")
        add("|---|---|---|---|---|")
        add(f"| Statistical gate (this harness) | `{report.incumbent.experiment.label}` "
            f"| {report.incumbent.result.val_mean:.4f} | {report.holdout_score:.4f} "
            f"| {report.selection_gap:+.4f} |")
        add(f"| Greedy `max` (canonical loop) | `{report.best_observed.experiment.label}` "
            f"| {report.best_observed.result.val_mean:.4f} | {report.greedy_holdout_score:.4f} "
            f"| {report.greedy_gap:+.4f} |")
        add("")

        same = report.incumbent.experiment.id == report.best_observed.experiment.id
        if same:
            add("Both rules selected the same pipeline, so the gate cost nothing on this "
                "study. That is the common case when one configuration is clearly best; "
                "the gate matters when several are within noise of each other, which is "
                "when a greedy loop starts reporting inflated numbers.")
        elif report.greedy_holdout_score < report.holdout_score:
            add(f"The greedy rule picked a pipeline whose validation score was "
                f"{report.best_observed.result.val_mean - report.incumbent.result.val_mean:+.4f} "
                f"higher but whose held-out score was "
                f"{report.greedy_holdout_score - report.holdout_score:+.4f} "
                f"**lower**. That difference is selection noise: with many trials, the "
                f"maximum observed validation score is a biased estimate of quality. "
                f"The gate avoided it by refusing improvements it could not distinguish "
                f"from chance.")
        else:
            add(f"On this study the greedy rule happened to do no worse on the held-out "
                f"set ({report.greedy_holdout_score:.4f} vs {report.holdout_score:.4f}). "
                f"One study is one sample: the gate reduces the *variance* of the "
                f"selection, so a single run can go either way. Its larger validation "
                f"gap ({report.greedy_gap:+.4f} vs {report.selection_gap:+.4f}) still "
                f"shows the inflation it would have reported.")
        add("")

    # ----------------------------------------------------------- leaderboard
    add("## Leaderboard (top 10 by validation score)")
    add("")
    add("| # | Pipeline | Validation | ± | Verdict | Fit (s) |")
    add("|---|---|---|---|---|---|")
    for rank, entry in enumerate(ledger.leaderboard(10), 1):
        marker = " ←selected" if (
            report.incumbent and entry.experiment.id == report.incumbent.experiment.id
        ) else ""
        add(f"| {rank} | `{entry.experiment.label}`{marker} "
            f"| {entry.result.val_mean:.4f} | {entry.result.val_std:.4f} "
            f"| {entry.verdict} | {entry.result.fit_seconds:.2f} |")
    add("")
    add("The top row of this table is *not* the selected pipeline unless marked. "
        "The maximum over many noisy measurements is biased upward; the selected "
        "pipeline is the one that survived a paired significance test.")
    add("")

    # ------------------------------------------------------ promotion chain
    accepted = ledger.accepted()
    if accepted:
        add("## How the incumbent evolved")
        add("")
        for entry in accepted:
            add(f"- **{entry.experiment.id}** → `{entry.experiment.label}` "
                f"({entry.result.val_mean:.4f})")
            add(f"  - *Hypothesis:* {entry.experiment.hypothesis.statement}")
            add(f"  - *Why accepted:* {entry.reason}")
        add("")

    # --------------------------------------------------- what was ruled out
    inconclusive = [e for e in ledger.entries if e.verdict == "inconclusive"]
    if inconclusive:
        add("## Recorded but not promoted")
        add("")
        add("These scored higher than the incumbent but not by enough to rule out "
            "chance. A greedy loop would have promoted every one of them.")
        add("")
        for entry in inconclusive[:8]:
            add(f"- `{entry.experiment.label}` — {entry.result.val_mean:.4f}: {entry.reason}")
        add("")

    failures = ledger.failures()
    if failures:
        add("## Failures")
        add("")
        add(f"{len(failures)} of {len(ledger.entries)} experiments failed. Failures are "
            "kept in the ledger and shown to the proposer, so the search learns from "
            "them instead of repeating them.")
        add("")
        for entry in failures[:8]:
            add(f"- `{entry.experiment.label}`: {entry.result.error}")
        add("")

    # ----------------------------------------------------- family discussion
    add("## By model family")
    add("")
    add("| Family | Tried | Failed | Best | Mean |")
    add("|---|---|---|---|---|")
    families = ledger.family_summary()
    for family in sorted(families, key=lambda f: -(families[f]["best"] or 0)):
        row = families[family]
        best = f"{row['best']:.4f}" if row["best"] is not None else "—"
        mean = f"{row['mean']:.4f}" if row["mean"] is not None else "—"
        add(f"| {family} | {row['n']} | {row['n_failed']} | {best} | {mean} |")
    add("")

    # ------------------------------------------------------------- protocol
    add("## Protocol")
    add("")
    add(f"- **Proposer:** {report.proposer_name}"
        + (f" ({report.fallback_count} fallback(s) to heuristic)"
           if report.fallback_count else ""))
    add(f"- **Validation:** repeated stratified k-fold, "
        f"{len(report.incumbent.result.fold_scores) if report.incumbent else '?'} "
        f"fits per experiment, identical folds for every experiment (fixed seed) "
        f"so comparisons are paired")
    add(f"- **Acceptance rule:** paired t-test at α={report.config.alpha}, "
        f"minimum effect {report.config.min_effect}")
    add(f"- **Held-out set:** scored exactly once, after the loop finished and the "
        f"winner was fixed")
    add(f"- **Budget:** {report.config.budget} experiments "
        f"({report.n_evaluations} evaluations used, {report.elapsed:.1f}s)")
    add(f"- **Seed:** {report.config.seed}")
    add("")
    add("### Threats to validity")
    add("")
    add("- One dataset and one study. The selection-rule comparison above is a single "
        "sample; `study.py --compare` repeats it across seeds.")
    add("- The held-out set is scored once, but it was split once too — a different "
        "split would move the final number by roughly its own standard error.")
    add("- The search space is fixed and declarative. The loop cannot invent a model "
        "family that is not in `search_space.py`, which is a deliberate safety "
        "boundary and a real ceiling on what it can discover.")
    add("")

    return "\n".join(lines)


def plot_study(report: StudyReport, out_dir: Path | None = None) -> Path:
    """Two panels: the search trace, and validation-vs-held-out for the finish."""
    out_dir = Path(out_dir or report.config.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{report.config.name}-trace.png"

    entries = report.ledger.entries
    figure, (left, right) = plt.subplots(
        1, 2, figsize=(13, 5), gridspec_kw={"width_ratios": [2.2, 1]}
    )

    # ---------------------------------------------------- panel 1: the trace
    colours = {"accepted": ACCEPT, "rejected": REJECT,
               "inconclusive": INCONCLUSIVE, "failed": MUTED}

    incumbent_trace: list[float] = []
    current = None
    for entry in entries:
        if entry.verdict == "accepted":
            current = entry.result.val_mean
        incumbent_trace.append(current if current is not None else float("nan"))

    for verdict, colour in colours.items():
        xs = [i for i, e in enumerate(entries, 1) if e.verdict == verdict and e.result.ok]
        ys = [e.result.val_mean for e in entries if e.verdict == verdict and e.result.ok]
        if xs:
            left.scatter(xs, ys, s=46, c=colour, label=verdict, zorder=3,
                         edgecolors="white", linewidths=0.8)

    left.step(range(1, len(entries) + 1), incumbent_trace, where="post",
              color=INCUMBENT, linewidth=2.2, label="incumbent", zorder=2)

    if report.best_observed is not None:
        left.axhline(report.best_observed.result.val_mean, color=MUTED,
                     linestyle=":", linewidth=1.4,
                     label=f"best observed ({report.best_observed.result.val_mean:.3f})")

    # A few bad configurations (an unscaled SVM, say) score near chance and
    # would compress the band where every decision actually happens. Clip to
    # the region of interest and say how many points fell outside it.
    scored = [e.result.val_mean for e in entries if e.result.ok]
    if scored:
        top = max(scored)
        lower = max(min(scored), top - 0.12)
        clipped = sum(1 for s in scored if s < lower)
        left.set_ylim(lower - 0.01, top + 0.012)
        if clipped:
            left.text(
                0.015, 0.03,
                f"{clipped} experiment(s) below {lower:.2f} not shown",
                transform=left.transAxes, fontsize=8.5, color=MUTED,
            )

    left.set_xlabel("experiment")
    left.set_ylabel("validation score")
    left.set_title("Search trace: what was tried, and what was accepted",
                   color=INK, fontsize=12, loc="left")
    left.legend(frameon=False, fontsize=9, loc="lower right")
    left.spines[["top", "right"]].set_visible(False)
    left.grid(axis="y", alpha=0.25, linewidth=0.6)

    # ------------------------------- panel 2: the number that actually counts
    if report.holdout_score is not None and report.incumbent is not None:
        labels = ["validation\n(selected)", "held-out\n(selected)"]
        values = [report.incumbent.result.val_mean, report.holdout_score]
        bar_colours = [INCUMBENT, ACCEPT]

        if report.greedy_holdout_score is not None and (
            report.best_observed.experiment.id != report.incumbent.experiment.id
        ):
            labels += ["held-out\n(greedy pick)"]
            values += [report.greedy_holdout_score]
            bar_colours += [REJECT]

        bars = right.bar(labels, values, color=bar_colours, width=0.6)
        for bar, value in zip(bars, values):
            right.text(bar.get_x() + bar.get_width() / 2, value + 0.004,
                       f"{value:.4f}", ha="center", fontsize=10, color=INK)

        low = min(values)
        right.set_ylim(max(0, low - 0.08), min(1.0, max(values) + 0.06))
        right.set_title("Validation vs reality", color=INK, fontsize=12, loc="left")
        right.spines[["top", "right"]].set_visible(False)
        right.grid(axis="y", alpha=0.25, linewidth=0.6)
    else:
        right.axis("off")
        right.text(0.5, 0.5, "no held-out set scored", ha="center", color=MUTED)

    figure.suptitle(f"Autoresearch study: {report.config.name}",
                    fontsize=14, color=INK, x=0.012, ha="left", weight="medium")
    figure.tight_layout(rect=[0, 0, 1, 0.94])
    figure.savefig(path, dpi=150, facecolor="white")
    plt.close(figure)
    return path
