"""An offline provider that behaves like a small, obedient model.

Why a fake model is part of the harness rather than the test suite:

  * The agent loop, tool dispatch, permission gate, compaction and transcript
    writer are harness code. None of them need a real model to be exercised --
    they need *something* that emits well-formed tool calls in a plausible
    order. That is cheap to write and makes the whole system deterministic.
  * It means `git clone && python -m minicoder "..."` works with no key, which
    is how anyone evaluating the repo will first run it.

It plans in phases: inspect the workspace, write the file it was asked for, run
it, then report. That is enough shape to drive a genuine end-to-end run in which
real files are really created and real commands really execute.
"""

from __future__ import annotations

import re
import uuid
from typing import Callable

from ..config import Config
from ..types import Completion, Message, ToolCall, Usage

PATH_RE = re.compile(r"[\w./-]+\.(?:py|txt|md|json|toml|ya?ml|cfg)")

FIZZBUZZ = '''"""Generated by the minicoder harness (mock provider)."""


def fizzbuzz(n: int) -> str:
    """Classic FizzBuzz for a single integer."""
    if n % 15 == 0:
        return "FizzBuzz"
    if n % 3 == 0:
        return "Fizz"
    if n % 5 == 0:
        return "Buzz"
    return str(n)


if __name__ == "__main__":
    print(" ".join(fizzbuzz(i) for i in range(1, 21)))
'''


class MockProvider:
    """Deterministic, offline, speaks the same Completion type as the real one."""

    name = "mock"

    def __init__(self, config: Config) -> None:
        self.config = config

    def complete(
        self,
        messages: list[Message],
        tools: list[dict] | None = None,
        stream: bool = False,
        on_text: Callable[[str], None] | None = None,
    ) -> Completion:
        available = {t["function"]["name"] for t in (tools or [])}
        task = next((m.text for m in messages if m.role == "user"), "")
        lowered = task.lower()

        # What have we already done this run? The mock reads its own history,
        # exactly as a real model reads the conversation to decide what is left.
        done = {
            call.name
            for m in messages
            if m.role == "assistant"
            for call in m.tool_calls
        }
        results = [m for m in messages if m.role == "tool"]
        paths = PATH_RE.findall(task)

        step = self._plan(lowered, paths, available, done)

        if step is None:
            text = self._summarise(task, results)
            if stream and on_text:
                for word in text.split(" "):
                    on_text(word + " ")
            return Completion(
                message=Message(role="assistant", content=text),
                finish_reason="stop",
                model="mock/scripted",
                usage=Usage(0, 0, 0),
            )

        name, args = step
        return Completion(
            message=Message(
                role="assistant",
                content=None,
                tool_calls=[
                    ToolCall(id=f"call_{uuid.uuid4().hex[:8]}", name=name, arguments=args)
                ],
            ),
            finish_reason="tool_calls",
            model="mock/scripted",
            usage=Usage(0, 0, 0),
        )

    # ------------------------------------------------------------------ planning

    def _plan(
        self, lowered: str, paths: list[str], available: set[str], done: set[str]
    ) -> tuple[str, dict] | None:
        """Return the next (tool, args), or None when the task looks finished."""

        wants_write = any(w in lowered for w in ("write", "create", "generate", "make"))
        wants_run = any(w in lowered for w in ("run", "execute", "test", "verify"))
        target = paths[0] if paths else "output.py"

        # Phase 1: look around before touching anything.
        if "list_dir" in available and "list_dir" not in done:
            return "list_dir", {"path": "."}

        # Phase 2: read a named file we are not about to overwrite.
        if paths and not wants_write and "read_file" in available and "read_file" not in done:
            return "read_file", {"path": target}

        # Phase 3: write what was asked for.
        if wants_write and "write_file" in available and "write_file" not in done:
            content = FIZZBUZZ if "fizzbuzz" in lowered else self._generic_module(lowered)
            return "write_file", {"path": target, "content": content}

        # Phase 4: prove it works.
        if wants_run and "bash" in available and "bash" not in done:
            command = f"python3 {target}" if target.endswith(".py") else "ls -la"
            return "bash", {"command": command}

        return None

    @staticmethod
    def _generic_module(lowered: str) -> str:
        return (
            '"""Generated by the minicoder harness (mock provider)."""\n\n\n'
            "def main() -> None:\n"
            f'    print("task was: {lowered[:60]}")\n\n\n'
            'if __name__ == "__main__":\n'
            "    main()\n"
        )

    @staticmethod
    def _summarise(task: str, results: list[Message]) -> str:
        if not results:
            return f"[mock] Nothing to do for: {task!r}"

        lines = [f"[mock] Completed the task using {len(results)} tool call(s):"]
        for index, result in enumerate(results, 1):
            preview = (result.text or "").strip().splitlines()
            head = preview[0][:90] if preview else "(empty)"
            lines.append(f"  {index}. {head}")
        lines.append(
            "\nSwap MINICODER_MOCK off and set OPENROUTER_API_KEY to run this with a real model."
        )
        return "\n".join(lines)
